controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Route de la page d'accueil
home:
    path: /
    controller: App\Controller\HomeController::index

# Route de la page "Ã€ propos"
about:
    path: /about
    controller: App\Controller\AboutController::index

# Route de la page CV
cv:
    path: /cv
    controller: App\Controller\CurriculumvitaeController::index